name: Sample Should Fail Run 1 Only
on: push
jobs:
  node-multiple-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]
    steps:
    - name: Log node version
      run: node -v
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}
    - name: Log Node version
      run: node -v