name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-lastest
    steps:
      - name: echo a string 
        run: echo "Hello World"
      - name: miltiline script
        run: |
          node -v
          npm -v
