name: Shell Commands
on: [pull_request]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    # needs: [name_of_job]
    steps:
      - name: echo a string 
        run: echo "Hello World"
      - name: miltiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
